### ISSUE TITLE
close runtests buffer with q

### ISSUE THREAD

**Issue by gustavnikolaj** [sunesimonsen/dotfiles#2]
I would like to be able to quit the buffer with the test output by a press on q or maybe the new fd chord.

I've tried to experiment a bit, but I haven't gotten it to work.

I guess we would need to create a mode for the buffer in order to make a binding for it?

**Comment by sunesimonsen** [comment]
This buffer should probably be backed on compilation mode: https://www.gnu.org/software/emacs/manual/html_node/emacs/Compilation-Mode.html

**Comment by sunesimonsen** [comment]
I updated .emacs to recognize stack traces from javascript and updated the runtests emacs plugin to use compilation mode. So now you can quit with q, navigate the stack traces and use follow mode. I also fixed that space does not search in compilation mode.
